name: Build and deploy to production

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/
      - run: npm install
      - run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.DEV_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.DEV_REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.DEV_REMOTE_PORT }}
          TARGET: /home/${{ secrets.DEV_REMOTE_USER }}/deploy/dev/frontend/
