name: Build and deploy review app

on:
  workflow_dispatch:
    inputs:
      refName:
        description: "Ref name"
        required: true
      dst:
        description: "Where to deploy"
        required: true

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.refName }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/
      - run: npm install
      - run: npm run build:staging

      - name: Create remote dir
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: mkdir -p /home/${{ secrets.REMOTE_USER }}/deploy/${{ github.event.inputs.dst }}/frontend/

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: /home/${{ secrets.REMOTE_USER }}/deploy/${{ github.event.inputs.dst }}/frontend/
